# Generated by Django 2.1.4 on 2018-12-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_room_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Room'),
        ),
    ]
