# Generated by Django 2.1.4 on 2018-12-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20181208_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='room',
        ),
    ]
