# Generated by Django 2.1.4 on 2018-12-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_session_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
